options:
  guami-mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the AMF.
    default: "208"
    required: true
  guami-mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the AMF.
    default: "99"
    required: true
  guami-region-id:
    type: string
    description: |
      The region ID of the AMF.
    default: "128"
    required: true
  guami-amf-set-id:
    type: string
    description: |
      The AMF set ID of the AMF.
    default: "1"
    required: true
  served-guami-0-mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the AMF.
    default: "208"
    required: true
  served-guami-0-mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the AMF.
    default: "99"
    required: true
  served-guami-0-region-id:
    type: string
    description: |
      The region ID of the AMF.
    default: "128"
    required: true
  served-guami-0-amf-set-id:
    type: string
    description: |
      The AMF set ID of the AMF.
    default: "1"
    required: true
  served-guami-1-mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the AMF.
    default: "460"
    required: true
  served-guami-1-mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the AMF.
    default: "11"
    required: true
  served-guami-1-region-id:
    type: string
    description: |
      The region ID of the AMF.
    default: "10"
    required: true
  served-guami-1-amf-set-id:
    type: string
    description: |
      The AMF set ID of the AMF.
    default: "1"
    required: true
  plmn-0-support-mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the AMF.
    default: "208"
    required: true
  plmn-0-support-mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the AMF.
    default: "99"
    required: true
  plmn-0-support-tac:
    type: string
    description: |
      The Tracking Area Code (TAC) of the AMF.
    default: "0x0001"
    required: true
  plmn-0-slice-0-sd:
    type: string
    description: |
      The Service Discovery (SD) of the AMF.
    default: "1"
    required: true
  plmn-0-slice-0-sst:
    type: string
    description: |
      The Service Selection (SS) of the AMF.
    default: "1"
    required: true
  plmn-0-slice-1-sd:
    type: string
    description: |
      The Service Discovery (SD) of the AMF.
    default: "124"
    required: true
  plmn-0-slice-1-sst:
    type: string
    description: |
      The Service Selection (SS) of the AMF.
    default: "111"
    required: true
  plmn-0-slice-2-sd:
    type: string
    description: |
      The Service Discovery (SD) of the AMF.
    default: "2"
    required: true
  plmn-0-slice-2-sst:
    type: string
    description: |
      The Service Selection (SS) of the AMF.
    default: "2"
    required: true
